version: '2'
services:
  web:
    image: blume-api:latest
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/blume_pages
    volumes: 
      - ./:/app
    ports:
      - 4567:4567
    links:
      - mongodb:mongodb
  mongodb:
    image: mongo:3.2
    ports:
      - "27017:27017"
    command: mongod --smallfiles
